### ISSUE TITLE
Feature request: Add multiline comment support

### ISSUE THREAD

**Issue by rempas** [jedekar/vim-vox#1]
I would appreciate it if you could do that. If not, is there a place where I can learn how to create a fully featured syntax file myself?

**Comment by jedekar** [comment]
@rempas so, as my inspiration I used Go's syntax file and the first article from [vim fandom](https://vim.fandom.com/wiki/Creating_your_own_syntax_files). You can also look through other syntax files.

Please, do not get into refactoring under this feature request, just add multiline comments support. We can address that with another PR.

Welcome aboard! Glad someone found this useful.

**Comment by rempas** [comment]
Thanks a lot! Yeah I'm closely watching Vox so your syntax file is super useful. I will make a pull request when I have time and implement them.
